Repository study-for-code/Backend, pull requests merged in 2024-06, with the labels that each got.

#3 feature/TGST-161
  spoco/src/main/java/goorm/spoco/domain/review/domain/Review.java
  spoco/src/main/java/goorm/spoco/domain/review/domain/ReviewStatus.java
Labels: feat

#2 feature/TGST-159
  spoco/src/main/java/goorm/spoco/domain/study/domain/Study.java
Labels: feat

#24 Feature/TGST-31
  spoco/src/main/java/goorm/spoco/domain/testcase/controller/TestcaseController.java
  spoco/src/main/java/goorm/spoco/domain/testcase/domain/Testcase.java
  spoco/src/main/java/goorm/spoco/domain/testcase/service/TestcaseService.java
Labels: feat

#26 feature/TGST-63
  spoco/src/main/java/goorm/spoco/domain/testcase/controller/TestcaseController.java
  spoco/src/main/java/goorm/spoco/domain/testcase/service/TestcaseService.java
Labels: feat, refactor

#32 feature/TGST-178
  spoco/src/main/java/goorm/spoco/domain/review/service/ReviewService.java
  spoco/src/main/java/goorm/spoco/global/common/BaseResponse.java
Labels: feat

#31 feature/TGST-99
  spoco/build.gradle
  spoco/src/main/java/goorm/spoco/domain/study/controller/StudyController.java
  spoco/src/main/java/goorm/spoco/domain/study/controller/request/CreateStudyReq.java
  spoco/src/main/java/goorm/spoco/domain/study/controller/response/CreateStudyRes.java
  spoco/src/main/java/goorm/spoco/domain/study/domain/Study.java
  spoco/src/main/java/goorm/spoco/domain/study/repository/StudyRepository.java
  spoco/src/main/java/goorm/spoco/domain/study/service/StudyService.java
  spoco/src/main/resources/application.properties
Labels: feat

#36 feature/TGST-47
  spoco/src/main/java/goorm/spoco/domain/algorithm/controller/AlgorithmController.java
  spoco/src/main/java/goorm/spoco/domain/algorithm/domain/Algorithm.java
  spoco/src/main/java/goorm/spoco/domain/algorithm/service/AlgorithmService.java
Labels: refactor

#37 feature/TGST-66
  spoco/src/main/java/goorm/spoco/domain/algorithm/controller/AlgorithmController.java
  spoco/src/main/java/goorm/spoco/domain/algorithm/service/AlgorithmService.java
  spoco/src/main/java/goorm/spoco/global/common/BaseResponse.java
Labels: feat, refactor

#38 feature/TGST-46
  spoco/src/main/java/goorm/spoco/domain/algorithm/controller/AlgorithmController.java
  spoco/src/main/java/goorm/spoco/domain/algorithm/repository/AlgorithmRepository.java
  spoco/src/main/java/goorm/spoco/domain/algorithm/service/AlgorithmService.java
  spoco/src/main/java/goorm/spoco/domain/testcase/controller/TestcaseController.java
Labels: feat

#48 Feature/TGST-65
  spoco/src/main/java/goorm/spoco/domain/category/controller/CategoryController.java
  spoco/src/main/java/goorm/spoco/domain/category/service/CategoryService.java
  spoco/src/main/java/goorm/spoco/domain/subscribe/controller/SubscribeController.java
  spoco/src/main/java/goorm/spoco/domain/subscribe/controller/request/SubscribeRequest.java
  spoco/src/main/java/goorm/spoco/domain/subscribe/domain/Subscribe.java
  spoco/src/main/java/goorm/spoco/domain/subscribe/domain/SubscribeStatus.java
  spoco/src/main/java/goorm/spoco/domain/subscribe/repository/SubscribeRepository.java
  spoco/src/main/java/goorm/spoco/domain/subscribe/service/SubscribeService.java
  spoco/src/main/java/goorm/spoco/global/status/Status.java
Labels: feat
